# Generated by Django 5.1.4 on 2025-01-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
