# Generated by Django 5.1.4 on 2025-01-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_userprofile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='caritem',
            name='combo_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='caritem',
            name='combo_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='combo_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='combo_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='combo',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='title_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_name_ru',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='storereview',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='storereview',
            name='text_ru',
            field=models.TextField(null=True),
        ),
    ]
